//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.


fn main() {
    println!("Project Euler #2");
    let mut num1=0;
    let mut num2=1;
    let mut sum=0;

    loop {
        let num=num1+num2;

        if num>4000000{
            break;
        }
        
        if num%2==0{
            sum=sum+num;
        }
        num1=num2;
        num2=num;
    }
    println!("Even sum: {}",sum);
}
